services:
  wordpress:
    build: ./wordpress
    ports:
      - "8081:81"
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspass
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspass
    volumes:
      - db_data:/var/lib/mysql

  django-sqli:
    build: ./django-sqli
    ports:
      - "8001:8001"

  calc-challenge:
    build: ./calc-challenge
    ports:
      - "5001:5001"
  lost-last:
    build: ./loSt-last
    ports:
      - "5002:5002"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 

volumes:
  db_data: