services:
  ctfd :
    build: ./CTFd
    environment:
    - SECRET_KEY=./CTFd/.ctfd_secret
    - UPLOAD_FOLDER=/var/uploads
    - LOG_FOLDER=/var/log/CTFd
    - DATABASE_URL=mysql+pymysql://root:ctfd@db/ctfd
    - REDIS_URL=redis://cache:6379
    - WORKERS=4
    ports: 
    - 8000:8000
    volumes:
    - ./CTFd:/var/uploads
    depends_on:
    - ctfd_db

  ctfd_db:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=ctfd
    - MYSQL_DATABASE=ctfd
    - MYSQL_USER=ctfd
    - MYSQL_PASSWORD=ctfd
    volumes:
    - ./CTFd/mysql:/var/lib/mysql

  wordpress:
    build: ./wordpress
    ports:
      - "8081:81"
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspass
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - wordpress_db

  wordpress_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspass
    volumes:
      - db_data:/var/lib/mysql

  django-sqli:
    build: ./django-sqli
    ports:
      - "8001:8001"

  calc-challenge:
    build: ./calc-challenge
    ports:
      - "5001:5001"

volumes:
  db_data: